### ISSUE TITLE
how can i make predictions on train data

### ISSUE THREAD

**Issue by ajinkya7895** [AutoViML/Auto_TS#100]
I need to make predictions for train and test both how can I do it
Like I need the predictions to be done on the train data as well not just the test data.
Now the predictions are done after the train data ends , what i want to know is whether i can make predictions for the start of training data as well

**Comment by AutoViML** [comment]
Check out the example_notebooks folder in the Github. It has plently of examples.
    On Friday, May 26, 2023 at 07:02:32 AM EDT, ajinkya7895 ***@***.***> wrote:  
 
 


I need to make predictions for train and test both how can I do it

**Comment by ajinkya7895** [comment]
Hi in none of the examples predictions have been made on the train data. I hope my question was clear. I need to make predictions on train and test data both and then concat both the results. How can i do that? Is there any way in the predict method by which I can make predictions which start from the start date of the training data, now predictions are made from the date after the train data ends.

**Comment by AutoViML** [comment]
You can feed the train data as a dataframe and use it that way. Currently you can use either a number or a dataframe when you use the predict method. Try using the dataframe. Examples can be found in the example_notebook folder.
