### ISSUE TITLE
Mac M1max

### ISSUE THREAD

**Issue by artarrifa** [AutoViML/Auto_TS#101]
this module does not work becouse this modules can not be installed
ModuleNotFoundError: No module named 'lightgbm'
prophet

**Comment by AutoViML** [comment]
Please go ahead and pip install lightgbm and prophet in your machine. That should solve itAuto Vimal
    On Friday, June 16, 2023 at 11:01:21 AM EDT, artarrifa ***@***.***> wrote:  
 
 


this module does not work becouse this modules can not be installed
ModuleNotFoundError: No module named 'lightgbm'
prophet

**Comment by AutoViML** [comment]
You can try:

!pip install prophet
!pip install lightgbm

I don't know why you need lightgbm but prophet is required. It's in requirements.txt
