### ISSUE TITLE
Change requirements to `pyyaml` instead of `pyyaml==5.4.1`

### ISSUE THREAD

**Issue by pranavvp16** [AutoViML/Auto_TS#104]
Build for `pyyaml==5.4.1` is disabled due to `cpython` updates. This makes installation of auto-ts fail and completely unusable currently. Let me know why is the `pyyaml` version specific to `5.4.1`, if there is no good reason I'll make PR from fork which will fix installation of `auto-ts`
[pyyaml issue](https://github.com/yaml/pyyaml/issues/736)

**Comment by AutoViML** [comment]
Hi @pranavvp16 👍 

yes go ahead and make PR and I'll approve it if it works. Can you please make sure that certain pyyaml dependencies are not violated with multiple versions (such as 5.4.1 and 6.0 etc.)? I don't want to approve the PR and have a bunch of people complain  it breaks things.
Thanks
Auto Vimal

**Comment by pranavvp16** [comment]
@AutoViML 
Creating a PR, as nothing seems to breaking with the upgrade in `pyyaml==6.0.1`, I tried running an example from this repository with my fork and everything works fine. Even installation of `auto-ts` has become easy in google collab now. Here is the [example](https://colab.research.google.com/drive/1sIseNEziCVSAMiU8C01Qeiz10szjz-JJ?usp=sharing)

And I have also worked with `pyyaml=6.0.1` version for a month and faced no errors. 

Please get this merged ASAP as there's a pending [PR](https://github.com/mindsdb/mindsdb/pull/7663) that needs this to be fixed

**Comment by AutoViML** [comment]
Hi @pranavvp16 
thanks for the pull request. I have made a slight change 👍 
Hope this helps
Auto Vimal

**Comment by pranavvp16** [comment]
@AutoViML awesome I neglected that thanks !. One more thing how much time will it take to reflect this change in `pip install auto-ts` as it is still trying to install the older version of Pyyaml
