### ISSUE TITLE
`pip install auto-ts` still tries to install `pyyaml==5.4.1`

### ISSUE THREAD

**Issue by pranavvp16** [AutoViML/Auto_TS#106]
Although we changed the `pyyaml` version in recent PR when installing with `pip` it falls back to older version of auto-ts. Pls make an update of the updated version which installs the latest version of `pyyaml`

**Comment by pranavvp16** [comment]
@AutoViML when are you going to release the latest version of `auto-ts` as said there's a PR depending on the newest release

**Comment by AutoViML** [comment]
Hi @pranavvp16 👍 
yes it has been uploaded to pypi with a new version. Can you please test and confirm?
Sorry for the delay.
Auto Vimal
