### ISSUE TITLE
Add `Auto_TS` to `conda-forge`

### ISSUE THREAD

**Issue by RoyiAvital** [AutoViML/Auto_TS#110]
Hi,

Any chance to have `Auto_TS` on `conda-forge`?

**Comment by AutoViML** [comment]
@sugatoray : can you help with this request?

**Comment by sugatoray** [comment]
@AutoViML Okay. I will look into it.

**Comment by AutoViML** [comment]
@sugatoray 👍 any updates???

**Comment by sugatoray** [comment]
@AutoViML: I scanned the library for potential areas of errors while creating conda-forge packaging. I have opened a PR to update the packaging of `auto-ts` first. This will help with conda-forge packaging and also fix its pypi-packaging issues. Once it is merged and the package on PyPI is updated, I will start the conda-forge packaging.

- PR: #111

**Comment by sugatoray** [comment]
Related Conda-Forge PR:

- https://github.com/conda-forge/staged-recipes/pull/26194 

@AutoViML please see my comments [here](https://github.com/conda-forge/staged-recipes/pull/26194#issuecomment-2087657880) and also please let me know if you have questions about the PR #111.

**Comment by AutoViML** [comment]
Hi @sugatoray 
👍 
I made all the changes you requested in your PR and even merged it. Do we have to do anything more for conda-forge? Can I close this?
Ram

**Comment by sugatoray** [comment]
@AutoViML Thank you. Good news: `auto-ts` has been added to conda-forge! 🎉

Please close this issue. 

Regards
Sugato.

**Comment by AutoViML** [comment]
Thank you so much for your kind help @sugatoray 👍 

@RoyiAvital : auto-ts has been added to conda-forge! Please test it and let me know.

Auto Vimal
