### ISSUE TITLE
Add `requirements.txt` and `LICENSE` file to tar.gz source on PyPI

### ISSUE THREAD

**Issue by sugatoray** [AutoViML/Auto_TS#112]
The `.tar.gz` source file on PyPI currently is missing the following two files:

- `requirements.txt`
- `LICENSE`

<img width="740" alt="image" src="https://github.com/AutoViML/Auto_TS/assets/10201242/ead3190c-cdf7-4e5f-8f40-356841701499">

Please update the PyPI package to include these files.

### What does this break? 

<a href="https://pypi.org/project/auto-ts/0.0.90/#files" /><img width="663" alt="image" src="https://github.com/AutoViML/Auto_TS/assets/10201242/5c8b5721-54c8-47ac-b3c2-d20a0a2e99c7"><a/>

If you try to install from the [source file][#pypi-source] (`.tar.gz`), after downloading it from PyPI, the installation would fail as the `setup.py` file tries to install the dependencies from the `requirements.txt` and since it cannot find them, the installation fails.

[#pypi-source]: https://pypi.org/project/auto-ts/0.0.90/#files

This impacts conda-forge packaging, for the same reason as above and in addition to that, the LICENSE file is necessary for conda-forge packaging as well. Including the LICENSE file in the package source file (`.tar.gz`) on PyPI ensures, maintaining conda-forge packaging from a single source of truth.

**Comment by AutoViML** [comment]
Hi @sugatoray
Thanks for flagging the issue 👍 
I have fixed it now and tar.gz supports LICENSE and requirements.txt - take a look at the latest version in pypi and let me know.
Thanks for all your help,
Auto Vimal
