### ISSUE TITLE
VAR Model: Make sure that we have a way to not rely on column order to determine the target

### ISSUE THREAD

**Issue by ngupta23** [AutoViML/Auto_TS#14]
https://github.com/AutoViML/Auto_TS/blob/196ad1fe9633a0935cc564884ff2247d7a2c8051/auto_ts/models/ar_based/var.py#L54-L54

**Comment by ngupta23** [comment]
I will take care of this. This is just for tracking purposes.

<Update the line above to point to the develop branch>

**Comment by AutoViML** [comment]
Closed
