### ISSUE TITLE
Hard Dependency tscv not included in installation.

### ISSUE THREAD

**Issue by ngupta23** [AutoViML/Auto_TS#33]
Hard Dependency https://pypi.org/project/tscv/ needs to be included in the package installation. This is missing from auto-ts 0.0.25

**Comment by ngupta23** [comment]
For now, it can be installed separately using the instructions here: https://github.com/WenjieZ/TSCV

**Comment by AutoViML** [comment]
I have added TSCV dependency now in requirements, it should be fixed now.

Please try again using the latest version:
"pip install auto_ts --ignore-installed --no-cache-dir"

That should upgrade your version and hopefully fixes it.
Ram

**Comment by AutoViML** [comment]
Fixed - just upgrade to the latest version by:
"pip install auto_ts --ignore-installed --no-cache-dir"
