### ISSUE TITLE
UnboundLocalError: local variable 'forecast_df_folds' referenced before assignment

### ISSUE THREAD

**Issue by agbaezehenry** [AutoViML/Auto_TS#34]
not sure why but I'm getting this error when using this function:
automl_model.fit()

**Comment by ngupta23** [comment]
Can you provide a minimally reproducible example?

**Comment by AutoViML** [comment]
Sorry for the problem. There was a minor typo in one of the files which
causes this problem. Has been fixed.
Please try again using the latest version:
"pip install auto_ts --ignore-installed --no-cache-dir"
That should upgrade your version and hopefully fixes it.
Ram

**Comment by AutoViML** [comment]
Fixed - just upgrade to the latest version by:
"pip install auto_ts --ignore-installed --no-cache-dir"
