### ISSUE TITLE
CV in time series?

### ISSUE THREAD

**Issue by irahulroy** [AutoViML/Auto_TS#35]
My question is more on the theoretical side. I see that the 'model.fit' allows to set CV during algorithm training. Does the CV include random sampling and reshuffling during the training phase, or is it more like rolling-origin cross-validation, where the time chronology is maintained? 

Thanks, 
Rahul

**Comment by ngupta23** [comment]
@rroy09 Random sampling and shuffling is not the the recommended method for CV in time series due to auto correlation issues. We use temporal cross validation similar to what is [described here](https://robjhyndman.com/hyndsight/tscv/).

**Comment by AutoViML** [comment]
Yes agreed. No random sampling is done.

We do expanding window cross validation. You can think of it as a time
window that is constantly expanding to the right.
Hope that helps
Ram

**Comment by irahulroy** [comment]
Yeah, thanks for the reply. Just wanted to confirm as random sampling is prohibited for time series data.
