### ISSUE TITLE
time_interval in notebook example should be 'M' not 'Month'

### ISSUE THREAD

**Issue by microprediction** [AutoViML/Auto_TS#36]
Time_interval in notebook example should be 'M' not 'Month' ??

**Comment by AutoViML** [comment]
Yes I’ll fix that. We will now follow pandas’ date-range frequency codes
since that is what FB Prophet uses and guessing it is not good. I would
rather do what the user wants in this case.
Ram

**Comment by AutoViML** [comment]
Fixed - just upgrade to the latest version by:
"pip install auto_ts --ignore-installed --no-cache-dir"
