### ISSUE TITLE
Sometimes the forecast populates 'yhat', other times it populates 'mean'

### ISSUE THREAD

**Issue by microprediction** [AutoViML/Auto_TS#37]
Sometimes the forecast populates 'yhat', other times it populates 'mean', depending on the choice. 

As a minor comment, a "hello world" example to predict the next value in a monthly or daily series would have unearthed this perhaps, and not leave the reader to guess which column is changed. Maybe I'm missing something but the intent of predict( ) isn't super clear in code or docs.  

Reproduced here: https://github.com/microprediction/timeseries-notebooks/blob/main/auto_timeseries_hello.ipynb

**Comment by AutoViML** [comment]
Yes this is being changed to "yhat" for all models. It should come in the next version 0.0.27. Stay tuned.

**Comment by AutoViML** [comment]
Changed  Auto_TS to return "yhat" for all models.

**Comment by AutoViML** [comment]
This has been fixed in Master copy.  Just upgrade to the latest version by:
"pip install auto_ts --ignore-installed --no-cache-dir"
