### ISSUE TITLE
Hello, I have problem issue with module 'dask.dataframe' has no attribute 'core'

### ISSUE THREAD

**Issue by KilJaeeun** [AutoViML/Auto_TS#40]
![image](https://user-images.githubusercontent.com/52051773/106415918-9f44fa00-6493-11eb-852d-8f6db807120a.png)

Hello, I am a student who is trying to use this library for the first time.
There is a problem with using the library, so I want to leave my issue.

Currently, I'm trying to use this library using google COLAB, but I don't think any of the autos libraries have `disk.dataframe.core.DataFrame`  deprescribed. Could you please check it? Or could you tell me which version of the disk I should use to use this library correctly?

In addition, data items are missing from the example of the Jupiter notebook presented as an example. I'd like you to confirm.

I admire the easy way to use this library.I really want to use this library. Please give me a quick.

**Comment by AutoViML** [comment]
KilJaeeun 👍 I 
I  would like to help - can you please send me an email to rsesha2001 at gmail  to give me access to your Colab notebook and a sample data so I can check it. Thanks
Ram

**Comment by AutoViML** [comment]
Hi:DASK is available in the latest version - please upgrade Auto-TS to the latest version by:
$ pip install auto-ts --upgrade
You should see version 0.0.36 and that should work.
ThanksRam

    On Sunday, January 31, 2021, 11:44:00 PM EST, 길재은 ***@***.***> wrote:  
 
 


Hello, I am a student who is trying to use this library for the first time.
There is a problem with using the library, so I want to leave my issue.
Currently, I'm trying to use this library using CORAB, but I don't think any of the autos libraries have disk.dataframe.core.DataFrame de-prescribed. Could you please check it? Or could you tell me which version of the disk I should use to use this library correctly?

**Comment by AutoViML** [comment]
Hi KilJaeeun :
Is there any way you can share 10 rows of your data here so I can test the problem ? Without data or how you are using Auto-TS it is impossible to trouble shoot a problem with minimal information like this. 

Please treat these forums like Stackoverflow. Please posta self contained piece of data and code to reproduce the problem.
Thanks
AutoViML Team
