### ISSUE TITLE
local variable 'mean_cv_score' referenced before assignment

### ISSUE THREAD

**Issue by tjc0726** [AutoViML/Auto_TS#42]
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-5-bedb03d5e001> in <module>
----> 1 model.fit( traindata=df_after, ts_column='Timestamp',target='Weighted_Price')

/usr/local/lib/python3.8/dist-packages/auto_ts/__init__.py in fit(self, traindata, ts_column, target, sep, cv)
    750         print(f"Total time taken: {elapsed:.0f} seconds.")
    751         print("-"*50 + "\n\n")
--> 752         print("Leaderboard with best model on top of list:\n",self.get_leaderboard())
    753         return self
    754 

/usr/local/lib/python3.8/dist-packages/auto_ts/__init__.py in get_leaderboard(self, ascending)
    904                         # else: # Assuming List
    905                         #     mean_cv_score = sum(cv_scores)/len(cv_scores)
--> 906                         mean_cv_scores.append(mean_cv_score)
    907 
    908                 results = pd.DataFrame({"name": names, self.score_type: mean_cv_scores})

UnboundLocalError: local variable 'mean_cv_score' referenced before assignment

---------------------------------------------------------------------------

So I think the problem is around line 898 in __init__.py
`
897                         elif isinstance(cv_scores, list):
898                             if len(cv_scores) == 0:
899                                 mean_cv_score =  np.inf
900                         else:
901                             mean_cv_score = self.__get_mean_cv_score(cv_scores)
902                         # if isinstance(cv_scores, float):
903                         #     mean_cv_score = cv_scores
904                         # else: # Assuming List
905                         #     mean_cv_score = sum(cv_scores)/len(cv_scores)
`
because it doesn't assign the value of mean_cv_score if len(cv_scores) is not equal to 0,I'm not an expert to this frame, but I saw a comment in line 905 says 'assuming list',maybe should put it below 899 like
`
897                         elif isinstance(cv_scores, list):
898                             if len(cv_scores) == 0:
899                                 mean_cv_score =  np.inf
900                             else:
901                                 mean_cv_score = sum(cv_scores)/len(cv_scores)
`

Just my guess

**Comment by AutoViML** [comment]
I have fixed this error in the ;latest version. Please pip install upgrade like this:

$ pip install auto-ts --upgrade --user

This should fix it  - if not, please reopen it.
Thx
Ram

**Comment by ssth81456** [comment]
https://github.com/AutoViML/Auto_TS/commit/fe029139e302d07b2fa1f1b1e9d647b120b086ee


---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-8-b1b0862cb977> in <module>
      4     target=target,
      5     cv=3,
----> 6     sep=sep)        

~\Anaconda3\envs\test\lib\site-packages\auto_ts\__init__.py in fit(self, traindata, ts_column, target, sep, cv)
    750         print(f"Total time taken: {elapsed:.0f} seconds.")
    751         print("-"*50 + "\n\n")
--> 752         print("Leaderboard with best model on top of list:\n",self.get_leaderboard())
    753         return self
    754 

~\Anaconda3\envs\test\lib\site-packages\auto_ts\__init__.py in get_leaderboard(self, ascending)
    904                         # else: # Assuming List
    905                         #     mean_cv_score = sum(cv_scores)/len(cv_scores)
--> 906                         mean_cv_scores.append(mean_cv_score)
    907 
    908                 results = pd.DataFrame({"name": names, self.score_type: mean_cv_scores})

UnboundLocalError: local variable 'mean_cv_score' referenced before assignment

**Comment by AutoViML** [comment]
Hello:I found the error and fixed it. Please upgrade via:
$ pip install auto-ts --upgrade
If you see the version number 0.0.36, it should work.Thanks for your patienceRam
    On Friday, March 12, 2021, 1:22:52 AM EST, ssth81456 ***@***.***> wrote:  
 
 


fe02913

UnboundLocalError Traceback (most recent call last)
 in 
4 target=target,
5 cv=3,
----> 6 sep=sep)

~\Anaconda3\envs\test\lib\site-packages\auto_ts_init_.py in fit(self, traindata, ts_column, target, sep, cv)
750 print(f"Total time taken: {elapsed:.0f} seconds.")
751 print("-"*50 + "\n\n")
--> 752 print("Leaderboard with best model on top of list:\n",self.get_leaderboard())
753 return self
754

~\Anaconda3\envs\test\lib\site-packages\auto_ts_init_.py in get_leaderboard(self, ascending)
904 # else: # Assuming List
905 # mean_cv_score = sum(cv_scores)/len(cv_scores)
--> 906 mean_cv_scores.append(mean_cv_score)
907
908 results = pd.DataFrame({"name": names, self.score_type: mean_cv_scores})

UnboundLocalError: local variable 'mean_cv_score' referenced before assignment

**Comment by ssth81456** [comment]
Thanks, updated to 0.0.36 and the issue is solved now.
