### ISSUE TITLE
Time Series column 'month' could not be converted to a Pandas date time column.

### ISSUE THREAD

**Issue by TahaSha** [AutoViML/Auto_TS#46]
When fitting the model I got this error:

```
module 'dask.dataframe' has no attribute 'core'
Error: Could not convert Time Series column to an index. Please check your input and try again
Time Series column 'month' could not be converted to a Pandas date time column.
                    Please convert your input into a date-time column  and try again
```

 My `train_data `has nothing but 2 columns; 'quantity' and 'month'. It is a monthly dataset and the month column was already a `datetime64[ns]` type

**Comment by AutoViML** [comment]
Hi TahaSha:
Is there any way you can share 10 rows of your data here so I can test the problem ? Without data or how you are using Auto-TS it is impossible to trouble shoot a problem with minimal information like this. 

Please treat these forums like Stackoverflow. Please posta self contained piece of data and code to reproduce the problem.
Thanks
AutoViML Team
