### ISSUE TITLE
Auto-ts crash when Building Prophet Model

### ISSUE THREAD

**Issue by darthnyte** [AutoViML/Auto_TS#47]
Hi Sir,

the Auto-TS function crashes and kill the python kernel when building the prophet model.

error appeared when creating

Fold Number : 1 --> Train Shape: 54 Test Shape: 5

---------------------------------------------------------------------------------------------------------------------
KeyError                                                                                                          Traceback(most recent call last)
KeyError: 'metric_file'

**Comment by AutoViML** [comment]
Hi 
I may have found the error and fixed it. Please upgrade via:

$ pip install auto-ts --upgrade

If you see the version number 0.0.36, it should work.
Thanks for your patience
Ram

    On Wednesday, March 10, 2021, 9:27:24 PM EST, darthnyte ***@***.***> wrote:  
 
 


Hi Sir,

the Auto-TS function crashes and kill the python kernel when building the prophet model.

error appeared when creating

Fold Number : 1 --> Train Shape: 54 Test Shape: 5

KeyError Traceback(most recent call last)
KeyError: 'metric_file'

**Comment by nithinreddyy** [comment]
I'm also facing same error in jupyter notebook. I tried upgrading the version also. But it's not working. The error is 

```
Running Facebook Prophet Model...
  Starting Prophet Fit
      No seasonality assumed since seasonality flag is set to False
  Starting Prophet Cross Validation
Max. iterations using expanding window cross validation = 5

Fold Number: 1 --> Train Shape: 1157 Test Shape: 61
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: 'metric_file'
```
