### ISSUE TITLE
Error fitting model... cv_scores comparison with np.inf

### ISSUE THREAD

**Issue by bernardo-rufino-dev** [AutoViML/Auto_TS#48]
Hi, getting error when fitting...

![image](https://user-images.githubusercontent.com/79673486/116829696-97bcec00-ab7b-11eb-85cf-ac608f50cb38.png)

Something wrong with the cv_scores dataframe.

Any help?

**Comment by AutoViML** [comment]
Hi @bernardo-rufino-dev 👍 
I have found the error and fixed it. Please run the upgraded version:

`pip install auto_ts --upgrade`

let me know.
Thanks
