### ISSUE TITLE
Can you add regressors, e.g. holidays?

### ISSUE THREAD

**Issue by vhpietil** [AutoViML/Auto_TS#50]
I don't know about the other models but one can use e.g. holiday regressors with Prophet. Can you use regressors with Auto_TS?

**Comment by AutoViML** [comment]
You can add a column to your dataset that adds "Is_Holiday" to it. This will help in ML problems. I know that FB Prophet lets you add a dictionary for Holidays. I will try to add it soon.

**Comment by BrandonKMLee** [comment]
Can setting Q (within PDQ) to 365 in a daily results table useful to fixing that problem, or is that generally a bad idea?

**Comment by AutoViML** [comment]
You can now add all FB Prophet parameters in Auto_TS as an input. See the documentation README file for details.
Auto Vimal
