### ISSUE TITLE
 UnboundLocalError: local variable 'forecast_df_folds' referenced before assignment

### ISSUE THREAD

**Issue by Smrithi10** [AutoViML/Auto_TS#51]
I referred https://github.com/AutoViML/Auto_TS/issues/39 and upgraded auto_ts .
auto-ts  version ----   0.0.36
Issue still persists. Could you please help me out here?

Time Interval is given as D
    Correct Time interval given as a valid Pandas date-range frequency...
WARNING: Running best models will take time... Be Patient...

==================================================
Building Prophet Model
==================================================

Running Facebook Prophet Model...
    Fit-Predict data (shape=(330, 2)) with Confidence Interval = 0.95...
  Starting Prophet Fit
       Adding daily seasonality to Prophet with period=12, fourier_order=15 and prior_scale=0.10
  Starting Prophet Cross Validation
Max. iterations using expanding window cross validation = 3

Fold Number: 1 --> Train Shape: 315 Test Shape: 5
Exception occurred while building Prophet model...
'StanModel' object has no attribute 'fit_class'
    FB Prophet may not be installed or Model is not running...
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-21-c09cae1e1a0b> in <module>
----> 1 model.fit(traindata=train[['Date','FWD, 97 %ile']], ts_column='Date', target='FWD, 97 %ile', cv=3)

~\Anaconda3\envs\fbenv\lib\site-packages\auto_ts\__init__.py in fit(self, traindata, ts_column, target, sep, cv)
    504 
    505             self.ml_dict[name]['model'] = model
--> 506             self.ml_dict[name]['forecast'] = forecast_df_folds
    507             self.ml_dict[name][self.score_type] = score_val
    508             self.ml_dict[name]['model_build'] = model_build

UnboundLocalError: local variable 'forecast_df_folds' referenced before assignment

**Comment by AutoViML** [comment]
Hi @Smrithi10 
Can you please provide a colab link or github link for the code and dataset that you are using? I am not sure where the error is coming from. Please send email to rsesha2001 at gmail if you keep getting this error.

Also there is a new version out, please upgrade and check:

`pip install auto_ts --upgrade`

Thanks
Ram
