### ISSUE TITLE
Exception occurred while building ML model...

### ISSUE THREAD

**Issue by AkremBENHRIZ** [AutoViML/Auto_TS#53]
why i have this issue when the auto ts try to run ML model "it returns object of type 'float' has no len()"
any help please

**Comment by AutoViML** [comment]
@AkremBENHRIZ

Can you please post a copy of the code that you have and/or a snippet of your dataset so I can figure out where the problem is.

Please feel free to paste a link to a Colab or Github also where the code and dataset is.
Thanks
