### ISSUE TITLE
Cross Validation 

### ISSUE THREAD

**Issue by ghost** [AutoViML/Auto_TS#54]
Hi, 

Thanks for the library 

The Cross-Validation that your package is doing the standard k-fold Cross-Validation method or the one with rolling windows that is more appropriate for Time Series (e.g. as in [here](https://robjhyndman.com/hyndsight/tscv/) )

**Comment by AutoViML** [comment]
Hi @msh855 👍 It is doing the rolling window cross validation as shown in the same link
https://robjhyndman.com/hyndsight/tscv/
Ram
