### ISSUE TITLE
Error: Must Give Valid Time Interval Frequency

### ISSUE THREAD

**Issue by RusticPotatoes** [AutoViML/Auto_TS#56]
Following autots_multivariate_example.ipynb , importing osrs json data from runelite (data sample at the end).  

When running model.fit I get the following error at the bottom (below the charts). 

> Time Interval is given as h
>     Error: You must give a valid time interval frequency from Pandas date-range frequency codes
> 

Here is my setup -
```
ts_column = 'timestamp'
target = 'avgHighPrice'
time_interval='h'
sep = ','
train = dataset[:(len(dataset)-200)]
test = dataset[(len(dataset)-200):]
print(train.shape, test.shape)
model = auto_timeseries(
    score_type='rmse',
    model_type='best', 
    verbose=2,
   time_interval=time_interval)

model.fit(
    traindata=train,
    ts_column=ts_column,
    target=target,
    cv=200,
    sep=sep)
```
Example data

```
timestamp | avgHighPrice | avgLowPrice | highPriceVolume | lowPriceVolume | id
2021-07-25 13:00:00 | 341 | 334 | 237103 | 114893 | 25849
2021-07-25 14:00:00 | 345 | 334 | 250817 | 179962 | 25849
2021-07-25 15:00:00 | 346 | 334 | 117453 | 45003 | 25849
2021-07-25 16:00:00 | 332 | 326 | 443369 | 253239 | 25849
```

**Comment by AutoViML** [comment]
@RusticPotatoes : Please note that we accept only upper case values for Time Interval Frequency as you can see below.

We use the following pandas date range frequency aliases that Prophet uses to make the prediction dataframe.
Hence, please note that these are the list of allowed aliases for frequency: ['B','C','D','W','M','SM','BM','CBM', 'MS','SMS','BMS','CBMS','Q','BQ','QS','BQS', 'A,Y','BA,BY','AS,YS','BAS,BYS','BH', 'H','T,min','S','L,ms','U,us','N']

Your time interval frequency is in lowercase and is "h". Please correct and re-run. Thanks
