### ISSUE TITLE
ERROR: Failed building wheel for fbprophet

### ISSUE THREAD

**Issue by kathirveln** [AutoViML/Auto_TS#57]
Hi, Can any one suggest right way to install the auto-ts package in python:3.9 version?

**Tried**:
pip install auto-ts
pip3 install auto-ts

I'm getting below error - 
Building wheel for fbprophet (setup.py) ... error
ERROR: Command errored out with exit status 1:

Also I'm tried to install the fbprophet package, but didn't work.

Thanks!

**Comment by AutoViML** [comment]
Installing fbprophet on Windows is hard. You should try conda install fbprophet like this:

conda install -c conda-forge fbprophet 

Once you do that, it will work.
