### ISSUE TITLE
Why is Forecast Period = 5?

### ISSUE THREAD

**Issue by DariaMishina** [AutoViML/Auto_TS#58]
Hello! 
try to predict future values, e.g. for next 7 days, but only 5 days for future is possible to predict. Last actual day is 15/08, so 1st day of prediction is 16/08, last day - 20/08.
![image](https://user-images.githubusercontent.com/61119856/129613431-b5f58e51-0654-4a83-a986-ccb1ef821ab8.png)
Could you be so kind to let me know where it is possible to increase number of future periods? To predict from 16/08 till 22/08

**Comment by AutoViML** [comment]
@DariaMishina 👍 
This has been fixed in the latest version. Please do:
"pip install auto-ts --upgrade --user"

That should fix it.
Thanks
Auto-TS team

**Comment by DariaMishina** [comment]
Thank you so much!
