### ISSUE TITLE
Prophet: Quarterly forecast displays wrong dates

### ISSUE THREAD

**Issue by bbbingu** [AutoViML/Auto_TS#59]
Using the prophet model to forecast QS dates seems to return the wrong dates. The data I have is formatted as a quarter start frequency e.g. '2017-03-01', '2017-6-01', but the predictions show intervals of 2018-01-01, 2018-04-01, 2018-07-01.

<img width="907" alt="Screen Shot 2021-08-22 at 3 22 54 AM" src="https://user-images.githubusercontent.com/20812804/130332785-389132d3-009c-4533-9a5a-990f1ba0d7c3.png">
<img width="1110" alt="Screen Shot 2021-08-22 at 3 22 05 AM" src="https://user-images.githubusercontent.com/20812804/130332762-c517147a-5d45-4a36-95f0-dea996fccb5f.png">

**Comment by AutoViML** [comment]
@bbbingu 👍 
This has been fixed in the latest version. Please do:
"pip install auto-ts --upgrade --user"

That should fix it.
Thanks
Auto-TS team
