### ISSUE TITLE
Control Iterations for a final run on best model

### ISSUE THREAD

**Issue by conradtan** [AutoViML/Auto_TS#61]
Hi after running using 'best', have received the below message:
_"Maximum number of iterations hit, may not be at an optima"_

Is there a way to trigger a final run using the best model, or at least passing explicitly, while specifying a larger number of iterations to tune? 
Currently seems too short.

**Comment by AutoViML** [comment]
Hi @conradtan 👍 
Thanks for the feedback. I have increased the size of data that it can handle using Dask XGBOOST. This is a major upgrade.

You might want to check it out. Please do the upgrade to latest version by:
pip install auto-ts --upgrade

Please confirm whether this helps with the problem.
Thanks
Auto_ViML

**Comment by AutoViML** [comment]
Hi @conradtan 👍 
I have upgraded the ML model to now do hyper parameter tuning with XGBoost parameters and it seems to prduce much better results than before. It also returns a highly tuned model. Take a look and let me know.

```pip install auto_ts --upgrade ```

Hope this helps
AutoViML
