### ISSUE TITLE
Prophet model is crashing with error 'metric_file' after upgrading the version also.

### ISSUE THREAD

**Issue by nithinreddyy** [AutoViML/Auto_TS#62]
Prophet model is crashing with the error 'metric_file' after upgrading the version also. The error is below

```
Running Facebook Prophet Model...
    Fit-Predict data (shape=(1262, 2)) with Confidence Interval = 0.95...
  Starting Prophet Fit
      No seasonality assumed since seasonality flag is set to False
  Starting Prophet Cross Validation
Max. iterations using expanding window cross validation = 3

Fold Number: 1 --> Train Shape: 1247 Test Shape: 5
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
KeyError: 'metric_file'
```

![1](https://user-images.githubusercontent.com/56256685/132662181-11251580-cf51-4150-bf0d-4aee51fe2cc5.PNG)

Can you please look into this issue?

**Comment by AutoViML** [comment]
Hi @nithinreddyy 👍 

This should be fixed with the latest version. please do:
pip install auto-ts --upgrade

Also check this latest notebook:
https://github.com/AutoViML/Auto_TS/blob/master/example_notebooks/autots_multivariate_example.ipynb
Thanks for your patience
AutoViML
