### ISSUE TITLE
How to tune the model?

### ISSUE THREAD

**Issue by nithinreddyy** [AutoViML/Auto_TS#63]
Hey Ram, i have one doubt. Is there any example or notebook to show how to tune the auto-ts model? Like we have tune option in pycaret, do we have any in auto-ts?

**Comment by AutoViML** [comment]
Hi @nithinreddyy 👍 
Once you get the ML model from Auto_TS, you can create your own GridSearchCV params and tune it.
Currently there are no easy ways to tune a Dask XGBoost model which is what I am using right now.
If things change, I will let you know

In the meantime, Please do the upgrade to the latest version with DASK by:
pip install auto-ts --upgrade

Please confirm that fixes the problem.
Thanks
Auto_ViML
