### ISSUE TITLE
Invalid Parameter format for verbosity expect int but value='None'

### ISSUE THREAD

**Issue by amirkhalesi** [AutoViML/Auto_TS#64]
Greetings.
This error occurs in the ML part of training, possibly due to update of XGboost library.
solution:
Auto_TS/auto_ts/models/build_ml.py/  :
line 194                model = XGBRegressor(n_estimators=400, verbosity=None, random_state=0)
to:                    model = XGBRegressor(n_estimators=400, verbosity=0, random_state=0)

line 214                model = XGBRegressor(n_estimators=400, verbosity=None, random_state=0)
to:                    model = XGBRegressor(n_estimators=400, verbosity=0, random_state=0)

fixes the problem

**Comment by AutoViML** [comment]
Hi @amirkhalesi 👍 
It is fixed now. Please do the upgrade to latest version by:
pip install auto-ts --upgrade

Please confirm that fixes the problem.
Thanks
Auto_ViML

**Comment by amirkhalesi** [comment]
> Hi @amirkhalesi +1 It is fixed now. Please do the upgrade to latest version by: pip install auto-ts --upgrade
> 
> Please confirm that fixes the problem. Thanks Auto_ViML

Thanks for the update.
It is currently fixed.
Closing the Issue
