### ISSUE TITLE
Trying to save the model!

### ISSUE THREAD

**Issue by alicascar** [AutoViML/Auto_TS#65]
Hi, Is there anyway to save the created model?

I tried to use `dill` but still it didn't help!

```
import dill
dill.dump(model, open('auto_ts.pkl', 'wb'), byref=True)
```

I get the following error:

`RecursionError: maximum recursion depth exceeded`

Thanks in advance.

**Comment by miggytrinidad** [comment]
Were you able to solve this ?

**Comment by AutoViML** [comment]
Hi @miggytrinidad 👍 

This has been solved - can you please check the following notebook for an example of how it works.
https://github.com/AutoViML/Auto_TS/blob/master/example_notebooks/autots_multivariate_example.ipynb
thx
AutoViML
