### ISSUE TITLE
How do you save the best model?

### ISSUE THREAD

**Issue by miggytrinidad** [AutoViML/Auto_TS#66]
I tried using pickle but it says lambda function cannot be saved into a pkl file. How do you save the best model?

**Comment by AutoViML** [comment]
Hi @miggytrinidad : 
If the best model is an ML model you can save it using Pickle. See the bottom of this notebook for an example of how to save a model:

https://github.com/AutoViML/Auto_TS/blob/master/example_notebooks/autots_multivariate_example.ipynb

**Comment by AutoViML** [comment]
This should be fixed with the latest version. please do:
pip install auto-ts --upgrade

Thanks for your patience
AutoViML
