### ISSUE TITLE
Using 'ML' parameter for model_type crashes Jupyter Kernel

### ISSUE THREAD

**Issue by Billeni07** [AutoViML/Auto_TS#68]
I was able to run a test Auto_TS using all model_type parameters, except for 'ML'. Within a few moments of using it, the Jupyter Notebook Kernel crashes and restarts. Any recommendations?
auto_ts version 0.0.43
yfinance version 0.1.66
Python version 3.8.8

Dependencies
numpy                              1.21.4
pandas                             1.3.4
xlrd                               2.0.1
scipy                              1.7.1
prettytable                        2.4.0
xgboost                            1.1.1
dask                               2021.10.0
matplotlib                         3.4.3
seaborn                            0.11.2
scikit-learn                       1.0.1
statsmodels                        0.12.2
pmdarima                           1.8.4
fbprophet                          0.7.1

**Comment by AutoViML** [comment]
Hi @Billeni07 👍 
I think there are some version mismatch issues with your machine.

Please look at the setup.py file and compare the requirements to your machine versions above. Then try this update.

Please do the upgrade to latest version by:
pip install auto-ts --upgrade

Please confirm that fixes the problem.
Thanks
Auto_ViML

**Comment by Billeni07** [comment]
Hi @AutoViML ! Thanks for responding and trying it out. I ran setup.py file and then did the upgrade. Running the autots_univariate_example crashes the Jupiter notebook kernel at step 7.

model = auto_timeseries(score_type='rmse',
                time_interval='M',
                non_seasonal_pdq=None, seasonality=False, seasonal_period=12,
                model_type=['best'],dask_xgboost_flag=False,
                verbose=2)
model.fit(traindata, ts_column,target)

I also used the ts_2.csv data file and refreshed files with Github desktop.

Is there something else I can try or provide more data about?
Thanks.
Billeni07

**Comment by AutoViML** [comment]
Hi @Billeni07 👍 

can you please try to create a Colab notebook or Kaggle kernel and run the same notebook with the same data and show me? I am not seeing this error in my machine or in those public notebooks. Please share your link. Thanks
