### ISSUE TITLE
build_prophet.py --> seasonal_period is unused - Check if this is needed or something is missing

### ISSUE THREAD

**Issue by ngupta23** [AutoViML/Auto_TS#7]
https://github.com/AutoViML/Auto_TS/blob/7fe0b499863570f64d45ce80c50cd5c6f2bfd1b4/auto_ts/models/build_prophet.py#L61-L61

**Comment by AutoViML** [comment]
Agreed, commented out.

**Comment by AutoViML** [comment]
seasonal_period now added to FB Prophet. Check new version 0.0.29 which
contains this.
Fixed - just upgrade to the latest version by:
"pip install auto_ts --ignore-installed --no-cache-dir"
