### ISSUE TITLE
About saving the model and load it to predict  

### ISSUE THREAD

**Issue by kennis222** [AutoViML/Auto_TS#72]
Hi contributor, 

I have followed the example instruction to save the model. After loading it to predict, it seems that the loading model does not display "predicted" results. The results of the second screenshot are the desired results, but the loading model does not perform the same. I am not sure which part I need to fix. Thank you. 

![Screen Shot 2022-01-20 at 3 01 12 PM](https://user-images.githubusercontent.com/48114411/150289711-de9ff495-b4bf-4396-bf7f-334339a52643.png)
![Screen Shot 2022-01-20 at 3 01 20 PM](https://user-images.githubusercontent.com/48114411/150289716-f995c385-a0c7-441f-93c1-4d31681d34bf.png)

**Comment by AutoViML** [comment]
Hi @kennis222 👍 
Your observation is correct. There may be one of two reasons for that oddity:

1. You might want to check if `best_model` indeed is a VAR model object. It may not be. But make sure.

2. The `predict()` function does a few steps to preprocess the data before feeding to a VAR model. That might be the reason for the change. 

Please check and let me know
AutoViML

**Comment by kennis222** [comment]
Hi contributor,
1. You are right. It seems that the best_model is not a VAR model, instead, the VARMAXResultsWrapper.
![Screen Shot 2022-01-21 at 11 28 33 AM](https://user-images.githubusercontent.com/48114411/150460726-d02412b2-6d2c-45df-a045-c07f277708f3.png)
![Screen Shot 2022-01-21 at 11 28 37 AM](https://user-images.githubusercontent.com/48114411/150460727-73246b3f-17d3-44cb-a68c-aec422d5a3f5.png)
2. I just double check the function of VARMAXResults.predict, and it works by entering the specific date. 
![Screen Shot 2022-01-21 at 11 41 27 AM](https://user-images.githubusercontent.com/48114411/150461768-b12f6924-b97d-42d1-a582-ec7cde0b7412.png)
Thank you 👍
