### ISSUE TITLE
error import auto_timeseries in colab

### ISSUE THREAD

**Issue by antlig** [AutoViML/Auto_TS#75]
![error](https://user-images.githubusercontent.com/23186883/153633280-af0fd3cd-5bbe-4ff1-9a54-acb00e122e5a.png)

**Comment by AutoViML** [comment]
Hi @antlig 👍 
Thanks for bringing this to my attention. I have now updated requirements.txt and setup.py.

You should do the following in colab in the same order:
```
!pip install auto-ts
!pip install pyyaml==5.4.1
!pip install dask distributed --upgrade
```
Then restart the runtime and import auto_timeseries as follows:
```
from auto_ts import auto_timeseries
```
That should work. Please confirm.
AutoViML

**Comment by antlig** [comment]
OK it works
Thanks so much
