### ISSUE TITLE
UnboundLocalError: local variable 'forecast_df_folds' referenced before assignment

### ISSUE THREAD

**Issue by antlig** [AutoViML/Auto_TS#76]
![error](https://user-images.githubusercontent.com/23186883/153875186-7bbd6616-45f0-4c4f-9a2c-c5946d67078c.png)

Hello,
I am using the auto_time series version: 0.0.64 and when I run the following code:

```
- model = auto_timeseries (score_type = 'rmse', time_interval = 'M', non_seasonal_pdq = None, seasonality = False,
         seasonal_period = 12, model_type = ['best'], verbose = 2, dask_xgboost_flag = 0)

- model.fit (traindata, ts_column, target)

I get the following error:
UnboundLocalError: local variable 'forecast_df_folds' referenced before assignment (see iimagine).

Doing a quick analysis, it would appear that the variable 'forecast_df_folds' is either not initialized on line 539 (auto_ts / __ init __. Py) or it needs to be renamed to 'forecasts'.

I use Google Colab notebook.

Thanks
AL

**Comment by AutoViML** [comment]
Hello @antlig 👍 
it appears that Facebook prophet is not installed on your colab machine. So please do this first and then re-run it. 
```
conda install -c conda-forge prophet
```
Then re-run it. 

If you cannot run conda, then use the link below to install fbprophet:

https://facebook.github.io/prophet/docs/installation.html

Please note that when the model has not run, then there are no forecasts and hence forecast_df_folds gives an error.
Thanks
Auto_TS

**Comment by antlig** [comment]
![prophet2](https://user-images.githubusercontent.com/23186883/154107260-2c14f843-8097-476b-a432-f82e1dac87c9.PNG)
![prophet](https://user-images.githubusercontent.com/23186883/154107268-80ac676f-8f89-41d0-bdf2-56ba83978b17.PNG)

Hello,
I have replicated the steps you indicated, but it still doesn't work. I ran a 'pip list' to see if Facebook prophet was present and as you can see from the image it is there.

**Comment by AutoViML** [comment]
Hi @antlig 👍 
In that case, let's look at the data. Can you please post a Colab link to your notebook or a GitHub link to your notebook so we can trouble shoot the data and the calling statement?
It's possible you are making some small mistake - I can see that "y" is not in the index error below that auto-ts is not finding your target variable. Can you please post your calling statement (how you call auto-timseries) and what the first few rows of data look like? 
https://user-images.githubusercontent.com/23186883/153875186-7bbd6616-45f0-4c4f-9a2c-c5946d67078c.png
Thanks
