### ISSUE TITLE
About predicted results of var model  

### ISSUE THREAD

**Issue by kennis222** [AutoViML/Auto_TS#78]
Hello developer,

I have used the package by using the VAR model. However, I have one confirmation would like to double check with you. According to the statistical theory, VAR model mostly requires the stationary series. In most case, we need to make the first difference on original time series to make stationary. After building the VAR model, we conduct the prediction. In this step, I would like to make sure that whether the predicted values belong to the first difference on original time series, and we need to revert back the differencing to get the forecast to original scale. Or, does the predicted results belong to the forecast of original scale? This is very important to me because I have been studying the problem for a few months, and I am going to write an analytical report by using the model. 

I tried to do the demo without using the package, just directly using statsmodel varmax model with same model parameters by fitting the first difference series, and reverted back the differencing. The predicted results are quite different. 

Much appreciate.

**Comment by AutoViML** [comment]
Hi @kennis222 👍 
You need to check the https://github.com/AutoViML/Auto_TS/blob/master/auto_ts/models/ar_based/build_var.py and see whether the var model here does what you are looking for.
AutoViML
