### ISSUE TITLE
auto_ts.py --> seasonal_order is not used anymore. Check if this is needed or if it can be deleted.

### ISSUE THREAD

**Issue by ngupta23** [AutoViML/Auto_TS#8]
https://github.com/AutoViML/Auto_TS/blob/ba20967980e1997a8ba1992776088289353cc581/auto_ts/auto_ts.py#L134-L134

**Comment by AutoViML** [comment]
Agreed. Commented out.

**Comment by AutoViML** [comment]
Fixed - just upgrade to the latest version (0.0.29) by:
"pip install auto_ts --ignore-installed --no-cache-dir"
