### ISSUE TITLE
Time Series Classification

### ISSUE THREAD

**Issue by shamilnabiyev** [AutoViML/Auto_TS#80]
Does Auto_TS support Time Series Classification tasks?

**Comment by AutoViML** [comment]
Hi @shamilnabiyev 👍 
Can you provide an example data set that you are working with if possible (a link or GitHub)?
Thanks
AutoViML

**Comment by shamilnabiyev** [comment]
Hey, @AutoViML 

I'd like to use Auto_TS on these datasets:

* [FordA](https://www.timeseriesclassification.com/description.php?Dataset=FordA)
* [FordB](https://www.timeseriesclassification.com/description.php?Dataset=FordB)
* [AI4I 2020 Predictive Maintenance Dataset](https://archive.ics.uci.edu/ml/datasets/AI4I+2020+Predictive+Maintenance+Dataset)

**Comment by AutoViML** [comment]
Hi @shamilnabiyev 👍 
Your links are good. I think it will work without any changes. Just use "ML" option only on Auto_TS. The rest of the options such as ARIMA etc were not designed to work with regression problems.
So please try it first and post any errors or results that you get.
Thanks
AutoViML

**Comment by shamilnabiyev** [comment]
Hi @AutoViML 
I've already tested the Auto_TS on some datasets to predict the values (regression) and it works well. According the documentation, the `auto_timeseries` class supports only two score types, `RMSE`, `Normalized RMSE`, which are applicable to regression tasks. I'm wondering how can I use `Accuracy` and `F1 Score` on the `auto_timeseries` class?

**Comment by AutoViML** [comment]
Hi @shamilnabiyev 👍 
yes you can try that and see. I tested one of your datasets and it was not even a time series dataset since it did not have a date-time column! I am not sure how I can help you at this point
Autovimal
