### ISSUE TITLE
Prophet 1.0.1 vs fbProphet

### ISSUE THREAD

**Issue by ghost** [AutoViML/Auto_TS#81]
Would we be able to upgrade to the newer version of Prophet, that is now just called prophet? It seems like it would be an easy fix overall that I would be happy to take on.

**Comment by AutoViML** [comment]
Hi @KarateKat95 👍 
This is a very good idea. Can you please create the changes in your forked version and submit a pull request with all the necessary changes? You have to test it first that your changes work!

Thanks
AutoViML

**Comment by KarateKat94** [comment]
I have completed that. Thanks!

**Comment by turkalpmd** [comment]
But doesn't work yet. I opened new pull request.

**Comment by ghost** [comment]
> But doesn't work yet. I opened new pull request.

@turkalpmd See #82, where I already made this pull request a few months ago. It just needs to be merged by @AutoViML.

**Comment by turkalpmd** [comment]
> > But doesn't work yet. I opened new pull request.
> 
> @turkalpmd See #82, where I already made this pull request a few months ago. It just needs to be merged by @AutoViML.

Yes, I want to trying this today but it didnt work properly, after that. To be honest, I created a new pull request without checking the issue section. Then I saw you did something similar.  I can delete it of course, but maybe a new notification will go away to @AutoViML . It is very easy changing. Thank you.

**Comment by AutoViML** [comment]
Hi @KarateKat95 and @turkalpmd 
Thank you so much for filing the pull requests. I am very concerned about changing from FBProphet to Prophet without testing it - can you guys please test it with a few datasets before I approve it? 👍 

I am sure it will work fine but just want to be sure. 
Thanks
AutoVimal

**Comment by turkalpmd** [comment]
> Hi @KarateKat95 and @turkalpmd Thank you so much for filing the pull requests. I am very concerned about changing from FBProphet to Prophet without testing it - can you guys please test it with a few datasets before I approve it? +1
> 
> I am sure it will work fine but just want to be sure. Thanks AutoVimal

I will testing this. But I didn't change any architecture, I changed just library name.

**Comment by ghost** [comment]
> > Hi @KarateKat95 and @turkalpmd Thank you so much for filing the pull requests. I am very concerned about changing from FBProphet to Prophet without testing it - can you guys please test it with a few datasets before I approve it? +1
> > I am sure it will work fine but just want to be sure. Thanks AutoVimal
> 
> I will testing this. But I didn't change any architecture, I changed just library name.

Thanks @turkalpmd; I will run a few tests with some datasets on my end as well this weekend.

**Comment by AutoViML** [comment]
Hi @KarateKat94 @turkalpmd 

Any updates? Is the upgrade and change from one version to another smooth? Can you please update the code everywhere there is an import statement of FB prophet to Prophet?

I'd like you to test it on a few datasets after installing and importing auto-ts with the new version of prophet in your computers. 

You can use [pypi-test.org](https://test.pypi.org/) by uploading and testing your new versions of auto-ts. Hope that helps,

Thank you  in advance 👍 
AutoVimal

**Comment by turkalpmd** [comment]
I was on-call this week. I can be doing some updates tomorrow. I don't know if I haven't tested the codes on GitHub before, but I'll learn. I'll fix all other import commands today. Thank you for your patience.
Kind regards.

**Comment by turkalpmd** [comment]
> Hi @KarateKat94 @turkalpmd
> 
> Any updates? Is the upgrade and change from one version to another smooth? Can you please update the code everywhere there is an import statement of FB prophet to Prophet?
> 
> I'd like you to test it on a few datasets after installing and importing auto-ts with the new version of prophet in your computers.
> 
> You can use [pypi-test.org](https://test.pypi.org/) by uploading and testing your new versions of auto-ts. Hope that helps,
> 
> Thank you in advance +1 AutoVimal




$ pip install git+git://github.com/AutoViML/Auto_TS

Collecting git+git://github.com/AutoViML/Auto_TS
  Cloning git://github.com/AutoViML/Auto_TS to /tmp/pip-req-build-0xdvyn41
  Running command git clone --filter=blob:none --quiet git://github.com/AutoViML/Auto_TS /tmp/pip-req-build-0xdvyn41
  fatal: unable to connect to github.com:
  github.com[0: 140.82.121.4]: errno=Connection timed out

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet git://github.com/AutoViML/Auto_TS /tmp/pip-req-build-0xdvyn41 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet git://github.com/AutoViML/Auto_TS /tmp/pip-req-build-0xdvyn41 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.





fbprophet contain just test/test_auto_ts.py line 18 and auto_ts/build_prophet.py line 19-22 32 and 545

this changing is very simple. unfortunately Git command and pip command doesnt work.

**Comment by AutoViML** [comment]
Hi @turkalpmd :
There is a simple way to install auto-ts without dependencies 👍 
```
pip install auto-ts --ignore-installed --no-deps
```
Then you can install FB prophet independently using the following command:
```
conda install -c conda-forge fbprophet
```
Hope this helps,
AutoVimal

**Comment by turkalpmd** [comment]
> Hi @turkalpmd : There is a simple way to install auto-ts without dependencies 👍
> 
> ```
> pip install auto-ts --ignore-installed --no-deps
> ```
> 
> Then you can install FB prophet independently using the following command:
> 
> ```
> conda install -c conda-forge fbprophet
> ```
> 
> Hope this helps, AutoVimal

I will try this weekend

**Comment by AutoViML** [comment]
Hi @turkalpmd @KarateKat94 
I have updated Auto_TS with the latest version of prophet 1.0 - please double check if this works and let me know
Thank you for all you pull requests and commitment!
AutoVimal

**Comment by turkalpmd** [comment]
I will try in next 24 hour :D. Thank you.

**Comment by turkalpmd** [comment]
Yes It is works perfect. But I found another bug from univariable notebook, and you must change pypi release, pypi installed old .68 version;

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/tmp/ipykernel_7312/3941123415.py in <module>
      4                 model_type=['best'],dask_xgboost_flag=False,
      5                 verbose=2)
----> 6 model.fit(traindata, ts_column,target)

~/.local/lib/python3.9/site-packages/auto_ts/__init__.py in fit(self, traindata, ts_column, target, sep, cv)
    573 
    574             self.ml_dict[name]['model'] = model
--> 575             self.ml_dict[name]['forecast'] = forecast_df_folds
    576             self.ml_dict[name][self.score_type] = score_val
    577             self.ml_dict[name]['model_build'] = model_build

UnboundLocalError: local variable 'forecast_df_folds' referenced before assignment
```
