### ISSUE TITLE
error on colab

### ISSUE THREAD

**Issue by gautambak** [AutoViML/Auto_TS#83]
```
# !pip3 install auto-ts
from auto_ts import auto_timeseries
```

install works fine but when I do the import I get:
---------------------------------------------------------------------------
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-26-090b3d39a267>](https://localhost:8080/#) in <module>()
      1 # try a different library
      2 # !pip3 install auto-ts
----> 3 from auto_ts import auto_timeseries

5 frames
[/usr/local/lib/python3.7/dist-packages/distributed/config.py](https://localhost:8080/#) in <module>()
     18 
     19 with open(fn) as f:
---> 20     defaults = yaml.load(f)
     21 
     22 dask.config.update_defaults(defaults)

TypeError: load() missing 1 required positional argument: 'Loader'
```

**Comment by PriyanshuRj** [comment]
You can use `!pip install pyyaml==5.4.1` to install exact version of pyyaml as used in the library
This solved the error for me

**Comment by PriyanshuRj** [comment]
You can also try installing tsvc using the command `!pip install tscv` for installing all the remaining missing packages

**Comment by AutoViML** [comment]
Hi @gautambak 👍 
The following three steps worked for me in Colab - do this one after another in each cell. 
```
!pip install auto-ts --no-deps --ignore-installed
!pip install 'fsspec>=0.3.3'
!pip install statsmodels
```
But please restart the runtime (look up in the Colab Runtime menu) after installing statsmodels and then do this:
```
from auto_ts import auto_timeseries
```

Voila! that worked for me.
Autovimal
