### ISSUE TITLE
How do I export the sample predictions of each model? I want to know all the prediction data

### ISSUE THREAD

**Issue by kkk8574990** [AutoViML/Auto_TS#85]
How do I export the sample predictions of each model? I want to know all the prediction data

**Comment by AutoViML** [comment]
Hi @kkk8574990 👍 
Thanks for trying out Auto_TS. It is clearly mentioned in this example notebook below how to complete predictions on test data and save it for an example Hackathon. 

https://github.com/AutoViML/Auto_TS/blob/master/example_notebooks/Auto_TS_Test_AV_Hack_TS_Rank_600.ipynb

Please check it out.
Thanks
Autovimal
