### ISSUE TITLE
ValueError: maxlag must be less than (nobs/2 - 1 - ntrend) where n trend is the number of included deterministic regressors

### ISSUE THREAD

**Issue by sachin03garg** [AutoViML/Auto_TS#86]
Error with Augmented Dickey-Fuller test version used in this library. 'maxlag' is set to 31 and cannot be overridden.

The same is updated in the statsmodels library. Please look at this issue: https://github.com/statsmodels/statsmodels/issues/3330

This happens in case of time series of smaller length probably less than 62.

**Comment by AutoViML** [comment]
Ok agreed. Please see the updated version 0.66 which you can upgrade via:
```
pip install git+git://github.com/AutoViML/Auto_TS
```
