### ISSUE TITLE
The way to set number of iterations for fbprophet model

### ISSUE THREAD

**Issue by medphisiker** [AutoViML/Auto_TS#88]
Hello, I get this message from fbprophet model

"Maximum number of iterations hit, may not be at an optima".

Is there way to increase iterations for it ?

**Comment by AutoViML** [comment]
Hi @medphisiker 👍 
Great suggestion. I have added "kwargs" to FB Prophet as input to auto_timeseries from now on. All you have to do is change your initial step where you define the FB prophet model in auto_timeseries as follows and you will be able to run them longer and using any FB Prophet model argument you select.

<a href="https://ibb.co/DGjpr7G"><img src="https://i.ibb.co/6vqBX4v/add-fb-prophet.png" alt="add-fb-prophet" border="0"></a>

Hope this helps. You need to upgrade to the latest version via:

```
pip install auto-ts --upgrade
```

**Comment by medphisiker** [comment]
Wow ! Thank you very much ! =)
It is very good and useful update )
And I think it makes this framework more agile )
