### ISSUE TITLE
build_prophet.py --> time_interval = 'S'  Should this be 'time_int' and not 'time_interval'

### ISSUE THREAD

**Issue by ngupta23** [AutoViML/Auto_TS#9]
https://github.com/AutoViML/Auto_TS/blob/ba20967980e1997a8ba1992776088289353cc581/auto_ts/models/build_prophet.py#L71-L71

**Comment by AutoViML** [comment]
Correct. Changed. thanks for catching it.

**Comment by AutoViML** [comment]
This has been fixed in the Master version.
just upgrade to the latest version(0.0.29)  by:
"pip install auto_ts --ignore-installed --no-cache-dir"
