### ISSUE TITLE
How do we know if the model is using external regressors during training ? How to check which external features are used 

### ISSUE THREAD

**Issue by vinitkothari24** [AutoViML/Auto_TS#93]

**Comment by vinitkothari24** [comment]
How do we know if the model is using external regressors during training ? How to check which external features are used

**Comment by AutoViML** [comment]
@vinitkothari24 
Thanks for trying out Auto_TS 👍 

Have you tried setting the `verbose` input to 1 or 2 to see if you get more outputs to explain the steps.

I think you should also check out the notebooks in the example notebooks section:
[example notebooks](https://github.com/AutoViML/Auto_TS/tree/master/example_notebooks)

Let me know if this still doesn't answer your question.
Auto Vimal
