### ISSUE TITLE
No module named 'fbprophet'

### ISSUE THREAD

**Issue by josesugahara** [AutoViML/Auto_TS#94]
Hello!

I was trying to import the auto_ts library, but even after trying to install the libraries I still get the erro:

ModuleNotFoundError: No module named 'fbprophet'

when I run the command:

from auto_ts import auto_timeseries

Has anyone ever found something similar?

**Comment by AutoViML** [comment]
Hi @josesugahara 
Thanks 👍 for trying out Auto_TS. 

You are getting the error since we use a library named FB Prophet (Google it!) to run Auto_TS. Can you please post a screenshot of the error or show me where it is erroring?

Thanks
Auto Vimal

**Comment by juandrinconkcc** [comment]
Hello @AutoViML 

the library fbprophet was changed for prophet. If you don't have it downloaded in your pc, you will not be able to get that package via pip/conda:


![image](https://user-images.githubusercontent.com/111448151/223481661-c1233db8-96df-4c50-8c68-3eac217ddfae.png)

**Comment by AutoViML** [comment]
Yes I have removed `fbprophet` from the the requirements.txt and setup.py files. So you don't need it anymore for auto-ts.

Can you please see if it works with the new `prophet`? 
Thanks
Auto Vimal

**Comment by juandrinconkcc** [comment]
Hello @AutoViML 

I uninstalled the package and installed it again. 

I used: pip install auto_ts
All fine.

but when I use the following line of code:
from auto_ts import auto_timeseries

![image](https://user-images.githubusercontent.com/111448151/224126893-40bfaa91-b818-4d2d-9cb2-bc85915ae57b.png)

**Comment by AutoViML** [comment]
Hi @josesugahara
Auto_TS has now been upgraded to the new Prophet. You can test the new version by upgrading  👍 
```
pip install auto_ts --user --upgrade
```

You must also ensure you have the new Prophet installed.
Please test it and let me know.
Thanks
Auto Vimal

**Comment by ravik4985** [comment]
I am still getting the same erro even after installing pip install auto_ts --user --upgrade


![image](https://user-images.githubusercontent.com/65692537/227528361-fbcb10ad-572d-4e89-9c36-bf53495465ed.png)

**Comment by AutoViML** [comment]
I think you have multiple versions of python or something that prevents your Jupyter Notebook from pulling in the right version of auto_ts from Python site_packages folder. I suggest you try some other machine or try colab instead.

I am closing this comment for now.
Auto Vimal

**Comment by AutoViML** [comment]
Can you please upgrade to the latest version of auto_ts and try it again? I have fixed all these prophet install issues.ThanksAuto Vimal
    On Friday, March 24, 2023 at 09:03:19 AM EDT, ravik4985 ***@***.***> wrote:  
 
 


I am still getting the same erro even after installing pip install auto_ts --user --upgrade
