### ISSUE TITLE
Import Error issue

### ISSUE THREAD

**Issue by mohsinrazadev** [AutoViML/Auto_TS#99]
I'm getting while using this command.
`from auto_ts import auto_timeseries`

Error is:
OSError: dlopen(Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib)
Reason: image not found

**Comment by AutoViML** [comment]
Hi @mohsinrazadev 
thank you for trying out Auto_TS👍 

There must be something wrong with your installation. Did you try `auto_ts` or `autots`? They are 2 different packages.

I tested it in my Colab and it shows Auto_TS working in Colab with just these three installs...

You can try the same in your machine:
```
!pip3 install auto-ts --no-deps --ignore-installed
!pip install 'fsspec>=0.3.3'
!pip install pmdarima
```
Auto Vimal

**Comment by mohsinrazadev** [comment]
Not fix it. I use a MacBook Air m1 is there any related issue?

**Comment by AutoViML** [comment]
Hi @mohsinrazadev 
I am closing this issue for now since a simple Google search throws up a number of links that are related to the Mac OS: see one example:
https://github.com/microsoft/LightGBM/issues/1369

I don't think is related to Auto-TS at all.
Thanks for trying our Auto-TS👍 
AutoVimal

**Comment by AutoViML** [comment]
MohsinThis should be due to some incompatible libraries specific to your machine. Please try Colab or Kaggle notebooks where this works. Take a look at the steps here:```!pip install auto-ts --no-deps --ignore-installed!pip install 'fsspec>=0.3.3'!pip install statsmodels --upgrade!pip install pmdarima```
AutoVimal
    On Wednesday, April 19, 2023 at 07:41:48 AM EDT, Mohsin Raza ***@***.***> wrote:  
 
 


Not fix it.
